namespace U5BFA.Libraries
{
    [default_interface]
    runtimeclass MouseEventReceivedEventArgs
    {
        MouseEventReceivedEventArgs(Windows.Foundation.Point point);
        Windows.Foundation.Point Point { get; };
    }

    [default_interface]
    runtimeclass SystemTrayIcon
    {
        SystemTrayIcon(String iconPath, String tooltip, Guid id);
        SystemTrayIcon(String iconPath, String tooltip, Guid id, Boolean isVisible);

        String IconPath;
        String Tooltip;
        Boolean IsVisible;
        Guid Id { get; };

        void Show();
        void Destroy();

        event Windows.Foundation.TypedEventHandler<SystemTrayIcon, Object> IconDestroyed;
        event Windows.Foundation.TypedEventHandler<SystemTrayIcon, MouseEventReceivedEventArgs> LeftClicked;
        event Windows.Foundation.TypedEventHandler<SystemTrayIcon, MouseEventReceivedEventArgs> RightClicked;
    }
}
