# Copyright (c) 0x5BFA. All rights reserved.
# Licensed under the MIT license.

name: TrayIconFlyout CD

on:
  workflow_dispatch:

env:
  WORKING_DIR:         '${{ github.workspace }}' # 'D:\a\TrayIconFlyout\TrayIconFlyout'
  SOLUTION_PATH:       '${{ github.workspace }}\src\TrayIconFlyout.slnx'
  WASDK_CSPROJ_PATH:   '${{ github.workspace }}\src\TrayIconFlyout.Wasdk\TrayIconFlyout.Wasdk.csproj'
  UWP_CSPROJ_PATH:     '${{ github.workspace }}\src\TrayIconFlyout.Uwp\TrayIconFlyout.Uwp.csproj'
  OUTPUT_DIR:          '${{ github.workspace }}\artifacts'
  WASDK_OUTPUT_DIR:    '${{ github.workspace }}\artifacts\wasdk'
  UWP_OUTPUT_DIR:      '${{ github.workspace }}\artifacts\uwp'

jobs:
  build-pack-publish:
    runs-on: windows-latest
    env:
      CONFIGURATION: 'Release'
      PLATFORM: 'x64'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          9.0.x
          10.0.x

    - name: Pack the project (WASDK)
      run: dotnet build $env:WASDK_CSPROJ_PATH -c $env:CONFIGURATION -a $env:PLATFORM -o $env:WASDK_OUTPUT_DIR

    - name: Pack the project (UWP)
      run: dotnet build $env:UWP_CSPROJ_PATH   -c $env:CONFIGURATION -a $env:PLATFORM -o $env:UWP_OUTPUT_DIR

    - name: Upload nupkg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuPkg artifacts
        path: |
          ${{ env.OUTPUT_DIR }}\**\*.nupkg
          ${{ env.OUTPUT_DIR }}\**\*.snupkg

    - name: Publish to NuGet.org
      run: dotnet nuget push ${{ env.OUTPUT_DIR }}\**\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
